name: ci

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format
        uses: make fmt
      - name: Build
        uses: make
      - name: Test
        run: make test
      - name: Benchmark
        run: make bench
